version: "3.8"

services:
  python:
    build:
      context: ./backend
      target: production
    # command: "gunicorn -k uvicorn.workers.UvicornWorker -c ./gunicorn.conf.py app.main:app"
    volumes:
      - backendlogs:/home/backend/app/logs
    env_file:
      - ./backend/.env.prod
    networks:
      - backend_network

  nginx:
    build: ./backend_nginx
    ports:
      - 7000:7000
    depends_on:
      - python
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  backendlogs:
