version: "3.8"

services:
  python:
    build:
      context: ./backend
      target: production
    volumes:
      - backendlogs:/home/backend/app/logs
    env_file:
      - ./backend/.env.prod
    networks:
      - backend_network

  nginx:
    build:
      context: ./backend_nginx
      target: bridge
    ports:
      - 8000:80
    depends_on:
      - python
    networks:
      - backend_network

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - 3000:80

networks:
  backend_network:
    driver: bridge

volumes:
  backendlogs:
