# This is a basic workflow to help you get started with Actions
name: Azure CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        # Build necessary images for the backend
        - run: |
            docker build backend/. -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/talk-less-noise:api-latest --target production
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/talk-less-noise:api-latest
            docker build backend_nginx/. -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/talk-less-noise:backend-nginx-bridge-latest --target bridge
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/talk-less-noise:backend-nginx-bridge-latest
            docker build backend_nginx/. -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/talk-less-noise:backend-nginx-localhost-latest --target localhost
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/talk-less-noise:backend-nginx-localhost-latest
            docker build frontend/. -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/talk-less-noise:react-latest -f frontend/Dockerfile.remote
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/talk-less-noise:react-latest
