# This is a basic workflow to help you get started with Actions
name: Azure CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        env:
          # Setting an environment variable with the value of a configuration variable
          ACR_NAME: ${{ vars.ACR_NAME }}
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          run: |
            az acr login --name $ACR_NAME
            docker build backend/. -t $ACR_NAME.azurecr.io/talk-less-noise:api-latest --target production
            docker push $ACR_NAME.azurecr.io/talk-less-noise:api-latest
            docker build backend_nginx/. -t $ACR_NAME.azurecr.io/talk-less-noise:backend-nginx-bridge-latest --target bridge
            docker push $ACR_NAME.azurecr.io/talk-less-noise:backend-nginx-bridge-latest
            docker build frontend/. -t $ACR_NAME.azurecr.io/talk-less-noise:react-latest -f frontend/Dockerfile.remote
            docker push $ACR_NAME.azurecr.io/talk-less-noise:react-latest
